### ISSUE TITLE
Recipes page for potential use cases

### ISSUE THREAD

**Issue by jbarr21** [InflationX/ViewPump#12]
Add a Wiki page with a list of use cases such as:
- Changing text in a TextView
- Hiding views with no content description
- Returning a different subclass (similar to AppCompat)

**Comment by hzsweers** [comment]
I think a really neat example would be to reimplement AppCompat's interception to demo how sleek the APK is

**Comment by jbarr21** [comment]
Another interesting example would be one that draws over views such as a ViewBoundsInterceptor

```kotlin
class ViewBoundsInterceptor : Interceptor {
  override fun intercept(chain: Chain): InflateResult {
    val result = chain.proceed(chain.request())
    result.view()?.let {
      if (it !is ViewGroup) {
        val drawable = ShapeDrawable(RectShape())
        drawable.paint.style = Style.STROKE
        drawable.paint.color = ColorUtils.setAlphaComponent(Color.RED, 190)
        drawable.paint.strokeWidth = 2 * it.resources.displayMetrics.density

        it.viewTreeObserver.addOnPreDrawListener {
          drawable.setBounds(0, 0, it.width, it.height)
          it.overlay.clear()
          it.overlay.add(drawable)
          true
        }
      }
    }
    return result
  }
}
```

**Comment by dvoiss** [comment]
@jbarr21 Another use case is satire / fun as is the case of a library I released this week:

https://github.com/dvoiss/android-geocities-theme

**Comment by hzsweers** [comment]
that's both amazing and terrifying

**Comment by jbarr21** [comment]
@dvoiss I think you've won best usage of this lib

**Comment by jbarr21** [comment]
this is now a thing: https://github.com/InflationX/ViewPump/wiki/Recipes
