### ISSUE TITLE
Changing Artefacts

### ISSUE THREAD

**Issue by sdoward** [InflationX/ViewPump#29]
It seems like you have published 2 versions of ViewPump with the same version number. This caused a few issues with our team. It seems the most recent version of 2.0.0 has some issues https://github.com/InflationX/ViewPump/issues/28 . It potentially has breaking API changes (we are still trying to diagnose this). But the original 2.0.0 did not have these issues.

This caused issues with different team members being unable to build and random CI machines failing. This is because some machines still have the old artefact cached and others pulled the new one.

How come you uploaded different artefacts with the same version? 

Will you be following semantic versioning in the future?

**Comment by jbarr21** [comment]
Thanks for pointing out that there were 2 tags for the 2.0. The old tag (v2.0.0) was pushed by another contributor incorrectly and did not represent an actual release. The old (2.0.0) tag was correctly pushed by me and represented the artifacts in the actual 2.0 release.

I have now renamed the old, correct 2.0.0 tag to v2.0.0 to match the 1.0 release tag and deleted the extra tag. The artifacts on maven central are unaffected and were only every cut once.

Per the release notes, the 2.0 release includes the library being migrated to AndroidX and Kotlin (hence the bumped major # for semvar). The Kotlin did introduce some issues (such as #28) and will be addressed separately with a new release. Sorry for any inconvenience that this has caused.

**Comment by sdoward** [comment]
I don't think that is correct. Artefacts were pushed to maven central, it's not just tags.. We changed our  dependencies to 2.0.0 on 31.12.2019. Now the versions and artefacts have changed we have reliable builds failing across team members and CI. 

Thats actually better for us. We can fix the issues or revert to v1. 

Anyways thanks for the reply. I think the best thing to do would be to provide the now disappeared artefact as '2.0.0-apha'. That way teams who are impacted can at least point to an artefact they did previously. Albeit with a change of dependencies
