### ISSUE TITLE
Consumer ProGuard rules are bad

### ISSUE THREAD

**Issue by JakeWharton** [InflationX/ViewPump#35]
As far as I can tell, this library does reflection but not on any of its own types. It's unclear why you are shipping ProGuard rules that retain the entire library, prevent it from being optimized, and prevent it from being obfuscated. Please remove the rules or make an effort to craft the narrowest rules that retain only what's needed.

**Comment by jbarr21** [comment]
Ah, thanks for catching this. It must've been an oversight from when it was migrated out of [Calligraphy](https://github.com/chrisjenx/Calligraphy/blob/master/calligraphy/consumer-proguard-rules.txt). I'll take a look at this

**Comment by JakeWharton** [comment]
I'm happy to also help narrow them down if I can in any way. Normally I'd
just send a PR but it's late and I'm not actually a user of the library.
Just passing by it inside of someone else's APK.

**Comment by ZacSweers** [comment]
yeah these probably carried over from the original calligraphy version and just "adapted" copying them with the viewpump package 😅
