### ISSUE TITLE
Fatal Exception: android.view.InflateException

### ISSUE THREAD

**Issue by dduvedi** [InflationX/ViewPump#61]
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$NameAndAttrsViewCreator.onCreateView (-ViewPumpLayoutInflater.java:290)
io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept (-FallbackViewCreationInterceptor.java:14)
io.github.inflationx.viewpump.internal.-InterceptorChain.proceed (-InterceptorChain.java:30)
io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept (CalligraphyInterceptor.java:18)
io.github.inflationx.viewpump.internal.-InterceptorChain.proceed (-InterceptorChain.java:30)
io.github.inflationx.viewpump.ViewPump.inflate (ViewPump.java:36)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.onCreateView (-ViewPumpLayoutInflater.java:169)
android.view.LayoutInflater.onCreateView (LayoutInflater.java:682)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.superOnCreateView (-ViewPumpLayoutInflater.java:233)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.access$superOnCreateView (-ViewPumpLayoutInflater.java:19)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$ParentAndNameAndAttrsViewCreator.onCreateView (-ViewPumpLayoutInflater.java:271)
io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept (-FallbackViewCreationInterceptor.java:14)
io.github.inflationx.viewpump.internal.-InterceptorChain.proceed (-InterceptorChain.java:30)
io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept (CalligraphyInterceptor.java:18)
io.github.inflationx.viewpump.internal.-InterceptorChain.proceed (-InterceptorChain.java:30)
io.github.inflationx.viewpump.ViewPump.inflate (ViewPump.java:36)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.onCreateView (-ViewPumpLayoutInflater.java:151)

**Comment by drob1984** [comment]
,??

**Comment by ZacSweers** [comment]
Not enough information
