### ISSUE TITLE
Out Of Memory Error

### ISSUE THREAD

**Issue by farzadazimipoor** [InflationX/ViewPump#62]
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 3096012 byte allocation with 1800472 free bytes and 1758KB until OOM
dalvik.system.VMRuntime.newNonMovableArray (VMRuntime.java)
androidx.appcompat.app.AppCompatDelegateImpl.onCreateView (AppCompatDelegateImpl.java:1457)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2ViewCreator.onCreateView (-ViewPumpLayoutInflater.kt:378)
io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept (-FallbackViewCreationInterceptor.kt:14)
io.github.inflationx.viewpump.internal.-InterceptorChain.proceed (-InterceptorChain.kt:30)
io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept (CalligraphyInterceptor.java:18)
io.github.inflationx.viewpump.internal.-InterceptorChain.proceed (-InterceptorChain.kt:30)
io.github.inflationx.viewpump.ViewPump.inflate (ViewPump.kt:36)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2.onCreateView (-ViewPumpLayoutInflater.kt:358)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:732)
android.view.LayoutInflater.inflate (LayoutInflater.java:511)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate (-ViewPumpLayoutInflater.kt:57)
android.view.LayoutInflater.inflate (LayoutInflater.java:415)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate (-ViewPumpLayoutInflater.kt:48)
androidx.databinding.DataBindingUtil.inflate (DataBindingUtil.java:126)
net.ibazzar.ibazzar.ui.main.poster.PostersPagingViewHolder$Companion.create (PostersPagingViewHolder.kt:194)
net.ibazzar.ibazzar.ui.main.poster.PostersPagingAdapter.onCreateViewHolder (PostersPagingAdapter.kt:56)
androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder (RecyclerView.java:7078)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1194)

**Comment by nathangnzls** [comment]
any fix for this?

**Comment by Amin-Said** [comment]
I faced the same issue on android 7 - Huwaei device 

 Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 576000012 byte allocation with 4194304 free bytes and 188MB until OOM
dalvik.system.VMRuntime.newNonMovableArray (VMRuntime.java)
android.graphics.BitmapFactory.nativeDecodeAsset (BitmapFactory.java)
android.graphics.BitmapFactory.decodeStream (BitmapFactory.java:701)
android.graphics.BitmapFactory.decodeResourceStream (BitmapFactory.java:508)
android.graphics.drawable.Drawable.createFromResourceStream (Drawable.java:1152)
android.content.res.ResourcesImpl.loadDrawableForCookie (ResourcesImpl.java:930)
android.content.res.ResourcesImpl.loadDrawable (ResourcesImpl.java:769)
android.content.res.Resources.loadDrawable (Resources.java:921)
android.content.res.TypedArray.getDrawable (TypedArray.java:983)
android.widget.ImageView.<init> (ImageView.java:164)
android.widget.ImageView.<init> (ImageView.java:152)
androidx.appcompat.widget.AppCompatImageView.<init> (AppCompatImageView.java:74)
androidx.appcompat.widget.AppCompatImageView.<init> (AppCompatImageView.java:69)
androidx.appcompat.app.AppCompatViewInflater.createImageView (AppCompatViewInflater.java:199)
androidx.appcompat.app.AppCompatViewInflater.createView (AppCompatViewInflater.java:119)
androidx.appcompat.app.AppCompatDelegateImpl.createView (AppCompatDelegateImpl.java:1551)
androidx.appcompat.app.AppCompatDelegateImpl.onCreateView (AppCompatDelegateImpl.java:1602)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2ViewCreator.onCreateView (-ViewPumpLayoutInflater.kt:378)
io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept (-FallbackViewCreationInterceptor.kt:14)
io.github.inflationx.viewpump.internal.-InterceptorChain.proceed (-InterceptorChain.kt:30)
io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept (CalligraphyInterceptor.java:18)
io.github.inflationx.viewpump.internal.-InterceptorChain.proceed (-InterceptorChain.kt:30)
io.github.inflationx.viewpump.ViewPump.inflate (ViewPump.kt:36)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2.onCreateView (-ViewPumpLayoutInflater.kt:358)
android.view.LayoutInflater$FactoryMerger.onCreateView (LayoutInflater.java:192)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:780)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:738)
android.view.LayoutInflater.rInflate (LayoutInflater.java:869)
android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:832)
android.view.LayoutInflater.inflate (LayoutInflater.java:518)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate (-ViewPumpLayoutInflater.kt:57)
android.view.LayoutInflater.inflate (LayoutInflater.java:426)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate (-ViewPumpLayoutInflater.kt:48)
com.syncApps.madridqtr.databinding.FragmentOrderServiceBinding.inflate (FragmentOrderServiceBinding.java:289)
com.syncApps.madridqtr.ui.main.OrderServiceFragment.onCreateView (OrderServiceFragment.kt:553)
androidx.fragment.app.Fragment.performCreateView (Fragment.java:2898)
androidx.fragment.app.FragmentStateManager.createView (FragmentStateManager.java:527)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1324)
androidx.fragment.app.FragmentManager.addAddedFragments (FragmentManager.java:2392)
androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:2137)
androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:2061)
androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:1957)
androidx.fragment.app.FragmentManager$5.run (FragmentManager.java:496)
android.os.Handler.handleCallback (Handler.java:761)
android.os.Handler.dispatchMessage (Handler.java:98)
android.os.Looper.loop (Looper.java:156)
android.app.ActivityThread.main (ActivityThread.java:6517)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:942)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:832)

**Comment by ZacSweers** [comment]
Not viewpump related, it just appears in the stacktrace because it participates in inflation and that was happening during your OOM.
