### ISSUE TITLE
Question: can this library help with integration of translation SDKs, such as Lokalise ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [InflationX/ViewPump#66]
I've noticed some edge cases that their SDK doesn't cover, such as inflation of Views (example is inflation via the class that extends Application, to show content on top using SAW permission) .

Could this library be used such that whenever the app needs to get an instance of Resources class, it would use the one of the SDK , including when inflating of Views ? 

I ask because I've found this article, saying it might help:

https://jitinsharma.com/posts/taming-android-resources-and-layoutinflater-for-string-manipulation/?q=cache:NtfvHgBjYAgJ:https://jitinsharma.com/posts/taming-android-resources-and-layoutinflater-for-string-manipulation/%20&cd=19&hl=en&ct=clnk&gl=il

**Comment by mtrakal** [comment]
Lokalise SDK (2.0, don't know, how about 1.x...) internally uses ViewPump. So I think, that ViewPump can do the same as Lokalise...

**Comment by ZacSweers** [comment]
Use discussions for questions like this
